# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherBoard

pod 'Alamofire', '~> 5.2'
pod 'NVActivityIndicatorView'

end
